version: "3.8"
services:
  gitlab:
    image: gitlab/gitlab-ce
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2289
    ports:
      - '8929:8929'
      - '2289:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
  gitlab-runner:
    image: gitlab/gitlab-runner
    volumes:
      - ./runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
