global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: spring-boot-demo
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['127.0.0.1:5000']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: ['health']
    static_configs:
      - targets: ['http://127.0.0.1:5000/actuator/health']
        labels:
          service: 'backend-1'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
